### ISSUE TITLE
Blood Magic crash

### ISSUE THREAD

**Issue by edenpc** [FrenchUranoscopidae/Hated_Mobs#13]
Entering a world with Blood Magic and Hated Mobs installed will cause the game to crash. I'm not sure if this is on Blood Magic's end or yours.
[crash-2019-04-12_13.50.27-server.txt](https://github.com/FrenchUranoscopidae/Hated_Mobs/files/3071479/crash-2019-04-12_13.50.27-server.txt)

**Comment by FrenchUranoscopidae** [comment]
Thanks for reporting the issue ! I'll look into this as soon as I can.

**Comment by jglrxavpok** [comment]
It seems to be on Blood Magics end.

**Comment by edenpc** [comment]
I will submit a ticket to the Blood Magic developer if that's the case.
