### ISSUE TITLE
Possible conflict with Blood Magic - PotionEventHandlers

### ISSUE THREAD

**Issue by Gamerbolts** [FrenchUranoscopidae/Hated_Mobs#14]
Hey there, I was using the newest version of Hated Mobs 1.4.1 and went to go spawn some of the mobs with spawn eggs and was greeted with a server crash

https://pastebin.com/e9JkkPHz

There is the log. Seems like it is a conflict with Blood Magic and PotionEventHandlers
Not sure if your mod or Blood Magic but wanted to let you know

**Comment by FrenchUranoscopidae** [comment]
Hello ! After looking at the crashlog, it seems that the issue does not come from my mod but from Blood Magic, thank you for reporting the issue nonetheless :)

**Comment by Gamerbolts** [comment]
Yep no problem, will post on Blood Magic's github, ty
