### ISSUE TITLE
Unable to see Silk Spiders on a server

### ISSUE THREAD

**Issue by FuzzyFoxe** [FrenchUranoscopidae/Hated_Mobs#18]
I've tested single player with "open to LAN" and with a dedicated server. Silk spiders don't render, but they can be heard, and occasionally the webs they make aren't sent to the other clients.

When you're the host of an open to LAN server, only you can see them, no one else who joins can see them. (And how I know about the cobwebs not spawning for other players is through this method).

Minecraft version: 1.12.2
Forge Version "forge-14.23.5.2847"
Method to reproduce: Join a server with Hated Mobs installed on it and find/make Silk spiders. They do not render.

(Happens with or without a resource pack)

Hope this can be fixed soon!

**Comment by FrenchUranoscopidae** [comment]
I've already noticed the problem, I will fix it for the next version of the mod ^^
Thank you for reporting the issue nonetheless !

**Comment by FuzzyFoxe** [comment]
Thanks for such a quick response! c:
Looking forward to the update~

**Comment by FrenchUranoscopidae** [comment]
Hello ! I've been trying to replicate the bug but I can't reproduce it. Do you know if you have the same config as your friend ? It could cause this kind of problems if spiders aren't activated in both...

**Comment by FuzzyFoxe** [comment]
Made sure we had the same config set up, yes. Spiders were enabled on both. Even tried hosting the opposite direction, the issue flipped on itself, I couldn't see the spiders, but they could.

If it helps, we were using twitch to put the mod in.

**Comment by FrenchUranoscopidae** [comment]
I will keep on trying, you are not the only person who encountered this bug so there must be something somewhere, I hope I will find it eventually ^^
