### ISSUE TITLE
Potential bug with Dynamic Surroundings and/or Presets

### ISSUE THREAD

**Issue by Neglevin** [FrenchUranoscopidae/Hated_Mobs#3]
I was going about my business one day when VanillaFix decided to notify me about a bug between this mod and Dynamic Surroundings and Presets. It didn't crash my game (knock on wood), but it might be helpful to look at. Here's the log in question: https://paste.dimdev.org/ukatamebux.mccrash

**Comment by jglrxavpok** [comment]
I will try to fix this for the next release. The system that allows mosquitos/spiders to go through some blocks is quite fragile so if you find more bugs like this, send them our way!

**Comment by Neglevin** [comment]
Will do! :)
