### ISSUE TITLE
Crashing w/ newest version

### ISSUE THREAD

**Issue by Gamerbolts** [FrenchUranoscopidae/Hated_Mobs#5]
Hi there, I just saw your mod and wanted to download it for a modpack I am creating. Upon loading the pack I got a crash. https://pastebin.com/yRxZnYWK

Any help is appreciated. Thank you!

**Comment by FrenchUranoscopidae** [comment]
Thank you for reporting the issue, I will investigate the problem.

**Comment by FrenchUranoscopidae** [comment]
Problem should be fixed in the 1.1.1 version, it will soon be available here (waiting for curseforge validation) : https://minecraft.curseforge.com/projects/hated-mobs/files/2634177

**Comment by Gamerbolts** [comment]
awesome! Thank you
