### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by Gamerbolts** [FrenchUranoscopidae/Hated_Mobs#6]
Hi again, I loaded up just fine on my client but my server crashed. Is this mod supposed to be server compatible?

https://pastebin.com/EASdgG8r

Thanks again!

**Comment by FrenchUranoscopidae** [comment]
It is supposed to be, but know that I'm ckecking the code, I realized I forgot to change something which might be causing the crash. I'll fix this as quickly as I can !

**Comment by FrenchUranoscopidae** [comment]
It should be fixed now. Thanks again for reporting the issue ! I hope it will be all good now :)
The new version will soon be available here : https://minecraft.curseforge.com/projects/hated-mobs/files/2634453

**Comment by Gamerbolts** [comment]
yay! Thank you!
