### ISSUE TITLE
Another Server crash

### ISSUE THREAD

**Issue by Gamerbolts** [FrenchUranoscopidae/Hated_Mobs#8]
Hello! I was running the new version 1.2.0 on my server and I was watching the console. it was preparing world then stopped a bit then crashed, the crash log was a generic serverstopped one but when I looked in the files a folder was saved called [invalid-world-save-hated-mobs]

I have attached the file here:

[invalid_world_save_hated_mobs.zip](https://github.com/FrenchUranoscopidae/Hated_Mobs/files/2570056/invalid_world_save_hated_mobs.zip)

Thanks again for all of your help. Hope this one can be solved. Very strange.

**Comment by FrenchUranoscopidae** [comment]
Hello ! I'm so sorry it crashed again, I will do my best to fix this as soon as I can !

**Comment by Gamerbolts** [comment]
Not a problem, take your time :)

**Comment by FrenchUranoscopidae** [comment]
After investigating the issue, I have to admit I have no idea what happened, could you please send me **all** log files if that happens again ?

**Comment by Gamerbolts** [comment]
Very strange, ok so I loaded up my modpack with HatedMobs again and got to the overworld. a bunch of messages on the corner popped up, here is a screenshot [(https://imgur.com/a/IFvp7Iy)](url)

I tried to place down a mob from a spawn egg and nothing would happen. I checked and there was a crashlog here [https://pastebin.com/JTxtasd0](url)

I have a mod that when the game crashes it doesn't crash to desktop just tells me the issue and continues running. Hope this new information helps. Thanks again!

**Comment by FrenchUranoscopidae** [comment]
Thanks for the crashlog, I will use a radical solution this time, it should nuke this kind of problem linked to the class that caused all the issues until now.
I didn't do it before because it's quite technical and pretty dirty but those crashes shall end once and for all !

**Comment by Gamerbolts** [comment]
Awesome! Thank you very much! Sorry for the trouble. but if it works in my modpack with 300 mods it should work with ANY modpack lol.

**Comment by FrenchUranoscopidae** [comment]
Hi ! The new version is now available here : https://minecraft.curseforge.com/projects/hated-mobs/files/2643406
It should fix the crashes linked to the mosquitos (They caused most of the crashes until now)

**Comment by Gamerbolts** [comment]
Thank you!
